driver=com.mysql.cj.jdbc.Driver
url-remote=jdbc:mysql://192.168.42.131:3306/mybatis?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
url-local=jdbc:mysql://192.168.198.110:3306/mybatis?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
username=wayne
password=wayne