driver=com.mysql.cj.jdbc.Driver
url-remote=jdbc:mysql://192.168.40.110:3306/mybatis??serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
url-local=jdbc:mysql://192.168.44.123:3306/mybatis??serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
username=wayne
password=wayne