package com.wayne.mybatis.mapper;

import com.wayne.mybatis.pojo.Emp;
import com.wayne.mybatis.pojo.EmpExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbg.generated Wed Aug 10 14:45:54 CST 2022
     */
    long countByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbg.generated Wed Aug 10 14:45:54 CST 2022
     */
    int deleteByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbg.generated Wed Aug 10 14:45:54 CST 2022
     */
    int deleteByPrimaryKey(Integer eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbg.generated Wed Aug 10 14:45:54 CST 2022
     */
    int insert(Emp row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbg.generated Wed Aug 10 14:45:54 CST 2022
     */
    int insertSelective(Emp row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbg.generated Wed Aug 10 14:45:54 CST 2022
     */
    List<Emp> selectByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbg.generated Wed Aug 10 14:45:54 CST 2022
     */
    Emp selectByPrimaryKey(Integer eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbg.generated Wed Aug 10 14:45:54 CST 2022
     */
    int updateByExampleSelective(@Param("row") Emp row, @Param("example") EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbg.generated Wed Aug 10 14:45:54 CST 2022
     */
    int updateByExample(@Param("row") Emp row, @Param("example") EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbg.generated Wed Aug 10 14:45:54 CST 2022
     */
    int updateByPrimaryKeySelective(Emp row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbg.generated Wed Aug 10 14:45:54 CST 2022
     */
    int updateByPrimaryKey(Emp row);
}